framework:
  messenger:
    failure_transport: failed

    serializer:
      default_serializer: messenger.transport.igbinary_serializer

    transports:
      failed:
        dsn: 'in-memory://'
        retry_strategy:
          max_retries: 0

      roadrunner:
        dsn: 'roadrunner://'
        options:
          queue_name: amqp # ... use amqp pipeline from roadrunner jobs
        retry_strategy:
          max_retries: 4
          delay: 4000
          multiplier: 2
          jitter: 0.2

      amqp:
        dsn: 'amqp://guest:guest@rabbitmq:5672'
        options:
          auto_setup: false
          verify: false
          exchange:
            name: 'skeleton_exchange'
            type: direct
            default_publish_routing_key: 'skeleton_queue'
          queues:
            'skeleton_queue':
              binding_keys: [ 'skeleton_queue' ]
        retry_strategy:
          max_retries: 4
          delay: 4000
          multiplier: 2
          jitter: 0.2

    routing:
      App\Shared\Presentation\Messenger\SimpleEvent: roadrunner
      App\Shared\Presentation\Messenger\FailedEvent: roadrunner

services:
  _defaults:
    autowire: true
    autoconfigure: true

  messenger.transport.igbinary_serializer:
    class: Roqmeu\Symfony\Messenger\Bridge\RoadRunner\Serialization\IgbinarySerializer

  messenger.transport.roadrunner.factory:
    class: Roqmeu\Symfony\Messenger\Bridge\RoadRunner\Transport\RoadRunnerTransportFactory
    tags: [messenger.transport_factory]
