monolog:
  handlers:
    stderr:
      type: stream
      path: "php://stderr"
      level: debug

when@dev:
  monolog:
    handlers:
      file:
        type: stream
        path: "%kernel.logs_dir%/skeleton.%kernel.environment%.log"
        level: debug
      console:
        type: console
        process_psr_3_messages: false
        channels: [ '!event', '!doctrine', '!console' ]
