baldinof_road_runner:
  kernel_reboot:
    strategy: [on_exception, max_jobs]
    allowed_exceptions:
      - Symfony\Component\HttpKernel\Exception\HttpExceptionInterface
    max_jobs: 1000
    max_jobs_dispersion: 0.1
  kv:
    storages:
      - memory
      - memcached

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # It's necessary to be able to run the Symfony Console without RoadRunner.
  Spiral\Goridge\RPC\RPCInterface:
    factory: ['App\Util\RoadRunner\SwitchableRPCFactory', 'fromEnvironment']
