version: "3"

rpc:
  listen: unix:///opt/socket/rr-rpc.sock

server:
  command: "php bin/server --silent"
  relay: unix:///opt/socket/rr-relay.sock

http:
  address: 0.0.0.0:80
  access_logs: true
  fcgi:
    address: tcp://0.0.0.0:9000
  pool:
    num_workers: 1

kv:
  memory:
    driver: memory
    config: { }
  memcached:
    driver: memcached
    config:
      addr: "/var/run/shared/memcached/memcached.sock"

logs:
  mode: development
  level: debug
