version: "3"

rpc:
  listen: unix:///opt/socket/rr-rpc.sock

server:
  command: "php bin/http --silent"
  relay: pipes

pool:
  debug: true

http:
  address: 0.0.0.0:80
  access_logs: true
  fcgi:
    address: tcp://0.0.0.0:9000
  pool:
    num_workers: 1

amqp:
  addr: amqp://guest:guest@rabbitmq:5672

jobs:
  num_pollers: 1
  consume: [ "amqp" ]
  pipelines:
    amqp:
      driver: amqp
      config:
        queue: skeleton_queue
        exchange: skeleton_exchange
        exchange_type: direct
        routing_key: skeleton_queue
  pool:
    num_workers: 1
    command: "bin/jobs messenger:consume roadrunner --silent"

kv:
  memory:
    driver: memory
    config: { }
  memcached:
    driver: memcached
    config:
      addr: "/var/run/shared/memcached/memcached.sock"

logs:
  mode: development
  level: debug
