version: "3"

rpc:
  listen: unix:///opt/socket/rr-rpc.sock

server:
  command: "php bin/server --silent"
  relay: pipes

pool:
  debug: true
  num_workers: 2

http:
  address: 0.0.0.0:80
  access_logs: true
  fcgi:
    address: tcp://0.0.0.0:9000
  pool:
    num_workers: 1

jobs:
  consume: [ "memory" ]
  pipelines:
    memory:
      driver: memory
      config: { }
  pool:
    num_workers: 1
    command: "bin/console messenger:consume --all --silent"

kv:
  memory:
    driver: memory
    config: { }
  memcached:
    driver: memcached
    config:
      addr: "/var/run/shared/memcached/memcached.sock"

logs:
  mode: development
  level: debug
