name: "symfony-roadrunner-skeleton-dev"

volumes:
  sock: {}

services:
  angie:
    build:
      context: ../../.
      dockerfile: ./deploy/dev/angie/Dockerfile
    ports:
      - 10086:80
    volumes:
      - ../../public:/usr/share/angie/html:ro
      - ./angie/angie.dev.conf:/etc/angie/angie.conf:ro
    depends_on:
      - php
    restart: no

  php:
    user: www-data
    build:
      context: ../../.
      dockerfile: ./deploy/dev/php/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEPLOYMENT: dev
      PHP_IDE_CONFIG: "serverName=symfony-roadrunner-skeleton.loc"
    ports:
      - 10084:80
    volumes:
      - ../../.:/opt/app:cached
      - sock:/var/run/shared
    restart: no
    depends_on:
      - memcached
    command: rr serve -c .rr.dev.yaml

  scheduler:
    user: www-data
    build:
      context: ../../.
      dockerfile: ./deploy/dev/php/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEPLOYMENT: dev
    volumes:
      - ../../.:/opt/app:cached
    restart: no
    depends_on:
      - memcached
    command: bin/console messenger:consume scheduler_default --silent

  memcached:
    user: root
    build:
      context: ./memcached
      dockerfile: ./Dockerfile
    volumes:
      - sock:/var/run/shared
    restart: no
    environment:
      MEMORY_LIMIT: 32
      THREADS: 1

  rabbitmq:
    image: rabbitmq:4.0-alpine
    restart: no
